insert into continent values (1,'Europa'), (2,'Asia'), (3,'America de Nord'), (4,'America de Sud'), (5,'Africa');
insert into continent values (1,'Europa'), (2,'Asia'), (3,'America de Nord');
insert into continent values (4,'America de Sud'), (5,'Africa');
insert into country values (1,'Romania', 1),(2,'Grecia', 1),(3,'Turcia', 1), (4,'Italia', 1), (5,'Spania', 1);
insert into country values (6,'Thailanda', 2), (7,'Japonia', 2), (8,'Singapore', 2), (9,'Maldive', 2);
insert into country values (10,'SUA', 3), (11,'Canada', 3), (12,'Mexic', 3);
insert into country values (13,'Brazilia', 4), (14,'Argentina', 4), (15,'Chile', 4);
insert into country values (16,'Egipt', 5), (17,'Tunisia', 5), (18,'Africa de Sud', 5), (19,'Maroc', 5);
insert into city values (1,'Constanta', 1), (2,'Brasov', 1), (3,'Atena', 2), (4,'Mikonos', 2), (5,'Antalia', 3), (6,'Istanbul', 3), (7,'Roma', 4), (8,'Milano', 4), (9,'Madrid', 5), (10,'Barcelona', 5);
insert into city values (11,'Phuket', 6), (12,'Bangkok', 6), (13,'Tokio', 7), (14,'Osaka', 7), (15,'Singapore', 8), (16,'Male', 9);
insert into city values (17,'New York', 10), (18,'Miami', 10), (19,'Toronto', 11), (20,'Montreal', 11), (21,'Cancun', 12), (22,'Mexico City', 12);
insert into city values (23,'Rio De Janeiro', 13), (24,'Sao Paulo', 13), (25,'Buenos Aires', 14), (26,'Mar Del Plata', 14), (27,'Santiago', 15), (28,'Antofagasta', 15);
insert into city values (29,'Hurghada', 16), (30,'Sharm El-Sheikh', 16), (31,'Monastir', 17), (32,'Tunis', 17), (33,'Durban', 18), (34,'Cape Town', 18), (35,'Marrakech', 19), (36,'Casablanca', 19);
insert into airport values (1, 'CND', 1), (2, 'OTP', 2),  (3, 'ATH', 3),  (4, 'JMK', 4),  (5, 'AYT', 5),  (6, 'IST', 6),  (7, 'FCO', 7),  (8, 'MXP', 8),  (9, 'MAD', 9),  (10, 'BCN', 10);
insert into airport values (11, 'HKT', 11),  (12, 'BKK', 12),  (13, 'NRT', 13),  (14, 'KIX', 14),  (15, 'SIN', 15),  (16, 'MLE', 16);
insert into airport values (17, 'JFK', 17),  (18, 'MIA', 18),  (19, 'YYZ', 19),  (20, 'YUL', 20),  (21, 'CUN', 21),  (22, 'MEX', 22);
insert into airport values (23, 'GIG', 23),  (24, 'GRU', 24),  (25, 'EZE', 25),  (26, 'MDQ', 26),  (27, 'SCQ', 27),  (28, 'ANF', 28);
insert into airport values (29, 'HRG', 29),  (30, 'SSH', 30),  (31, 'MIR', 31),  (32, 'TUN', 32),  (33, 'DUR', 33),  (34, 'CPT', 34),  (35, 'RAK', 35),  (36, 'CMN', 36);
insert into hotel values (1, 'Hotelul Ramada by Wyndham Constanta este situat în Mamaia,pe malul lacului Tăbăcăria, la mai puțin de 10 minute de mers pe jos de plajă și la 500 de metri de Satul de Vacanță', 'Ramada Wyndham Constanta', 'FIVE_STARS', 1);
insert into hotel values (2, 'New Royal oferă cazare de 4 stele în Constanța, la 5 km de centrul comercial Tom Constanța și la 6 km de portul de agrement și clubul de iahturi Tomis.', 'New Royal', 'FOUR_STARS', 1);
insert into hotel values (3, 'Situat în nordul staţiunii Eforie Nord, lângă promenadă şi plaja cu nisip, Hotelul Mirage oferă o piscină interioară, precum şi tratamente spa şi wellness, la un cost suplimentar.', 'Mirage Medspa Hotel', 'THREE_STARS',1);
insert into hotel values (4, 'Hotelul Rainer se află la numai 5 minute de mers cu maşina de centrul oraşului Braşov şi beneficiază de o locaţie plăcută şi liniştită, cu legături bune spre oraşul vechi şi centrul comercial.', 'Hotel Rainer', 'THREE_STARS', 2);

insert into hotel values (5, 'Situat în apropiere de centrul de afaceri, financiar, cultural şi comercial al orașului,acest hotel nou oferă o ambianță luxoasă de 4 stele, bucătărie rafinată şi servicii impecabile.', 'Hotel HP Tower One', 'FOUR_STARS', 2);

insert into hotel values (6,'Hotelul Grand se află într-o zonă rezidențială liniștită din Brașov, înconjurată de munți frumoși. Proprietatea oferă sejur relaxant, plăcut.', 'Grand Hotel', 'FOUR_STARS', 2);

insert into hotel values (7,'Hotelul Giolli oferă camere mari, cu acces la internet Wi-Fi, servicii prietenoase şi recepţie cu program non-stop. Acesta este situat pe Via Nazionale, la mică distanţă de mers pe jos de Gara Termini din Roma. Atât Opera din Roma cât şi Fontana di Trevi se găsesc la câţiva paşi de Giolli. Staţia de metrou Repubblica este la 200 de metri distanţă. Camerele Hotelului Giolli sunt liniştite şi dotate cu aer condiţionat, TV prin satelit, uscător de păr şi minibar. Podelele sunt cu parchet din lemn eco-friendly, iar unele camere au balcoane cu vedere la strada principală. Micul dejun este servit în sala de mese panoramică. Hotelul are, de asemenea, un bar şi un salon confortabil. Personalul poate aranja transferuri la aeroport şi poate face rezervări pentru bilete de muzeu.','Hotel Giolli Nazionale','THREE_STARS', 7);

insert into hotel values (8,'Amenajat cu o terasă şi o grădină, Smooth Rome West este un hotel modern, care oferă camere la preţuri accesibile şi servicii profesioniste pe istorică Via Aurelia. Staţia de metrou Cornelia este la câţiva paşi. Proprietatea asigură acces gratuit la internet WiFi. Mobilate complet, camerele hotelului Smooth Rome West sunt dotate cu aer condiţionat. Fiecare cameră are TV prin satelit, minibar şi seif. Există şi o baie privată. În plus, hotelul Smooth oferă un bar şi 2 săli de conferinţe.','Smooth Hotel Rome West','FOUR_STARS',7);

insert into hotel values (9,'This property offers a Special Protection Program, a strict program of precise safeguards dedicated to our guests and our staff. Set 5 km from Milans city centre, Hotel Mirage Sure Hotel Collection by Best Western offers free WiFi throughout and en suite rooms with satellite Smart TV. Milan Villapizzone Station is 2 km from the hotel. Wooden furnished rooms include a minibar, a Smart TV with free SKY channels and parquet floors. The hotel serves a rich buffet breakfast every morning, and guests can enjoy a drink at the bar. This Best Western hotel is 4 km from San Siro stadium and 5 minutes drive from the MICO Congress Centre. A tram stopping in front of the property reaches Lanza Metro Station, 4 km away.','Hotel Mirage','FOUR_STARS',8);

insert into hotel values (10,'Vincci Capitol se află pe bulevardul Gran Via din Madrid, la câţiva metri de staţia de metrou Callao. Acest hotel elegant oferă camere cu TV cu ecran plat și o terasă pe acoperiș, cu vedere impresionantă la oraș. Hotelul Capitol are design în stil art deco şi camere spaţioase, izolate fonic, cu aer condiţionat. Toate au meniu de perne, minibar şi uscător de păr. Accesul WiFi este gratuit în toate zonele.Micul dejun servit zilnic include produse fără gluten. Districtul popular Puerta del Sol, cu numeroase baruri şi restaurante, este situat la numai 500 de metri de hotel. Plaza Mayor se află la 10 minute de mers pe jos.','Vincci Capitol ','FOUR_STARS',9);

insert into hotel values (11, 'Sunteți eligibil(ă) pentru un discount Genius la The Athens Gate Hotel! Pentru a economisi la această proprietate, trebuie doar să vă autentificați. Acest hotel are o poziţie prestigioasă în centrul istoric al Atenei. Oferă facilităţi de 4 stele, vedere excelentă la Acropole şi la Templul lui Zeus Olimpianul, precum şi preparate culinare excelente. Conexiunea WiFi este gratuită în toate zonele. Hotelul Athens Gate se află la 200 de metri de noul muzeu Acropole. Este situat vizavi de Templul lui Zeus Olimpianul, la intrarea în zona istorică Plaka.La ultimul etaj al hotelului există un bar-restaurant cu vedere impresionantă la oraş. Micul dejun poate fi servit la restaurantul de pe acoperiş sau poate fi comandat prin room service. În zona recepţiei puteţi găsi un bar care serveşte cafea, băuturi şi gustări uşoare pe tot parcursul zilei. Toate camerele din faţă au vedere la Templul lui Zeus Olimpianul, iar camerele din spate, de la etajele 6 şi 7, oferă vedere superbă la Acropole. Camerele cu vedere la Acropole sunt alocate la cerere şi în funcţie de disponibilitate. Toate unităţile sunt dotate cu TV LCD cu ecran plat de 27 inch', 'The Athens Gate Hotel', 'FOUR_STARS', 3);

insert into hotel values (12, 'Royalty Hotel Athens se află în Atena, la 100 m de Piața Monastiraki și oferă un bar, o terasă și vedere la oraș. Există diverse facilități, printre care un restaurant, recepție deschisă non-stop, room service și WiFi gratuit în întreaga proprietate. Hotelul are camere de familie.Toate camerele sunt prevăzute cu aer condiționat, TV cu ecran plat cu canale prin satelit, ceainic, birou, bideu și uscător de păr. Toate camerele hotelului sunt dotate cu dulap și baie privată.La Royalty Hotel Athens se poate lua un mic dejun tip bufet sau continental. La proprietate există un salon de coafură și un centru de afaceri.  Printre punctele de interes populare din apropierea cazării se numără piața de vechituri Monastiraki, Agora Romană și zona comercială Strada Ermou. Cel mai apropiat aeroport este Aeroportul Elefthérios Venizélos, situat la 20 km de Royalty Hotel Athens.','Royalty Hotel Athens', 'FOUR_STARS', 3);

insert into hotel values (13, 'Cu vedere la Morile de Vânt din Mykonos, Poseidon Hotel Suites se află la numai 50 de metri de plaja Megali Ammos. Hotelul de 3 stele oferă o piscină cu apă dulce şi camere luminoase cu aer condiţionat şi ventilator. Toate camerele cicladice se deschid în balcoane private cu vedere la oraşul Mykonos, la mare şi la insula Delos. Fiecare cameră dispune de frigider, TV prin satelit şi seif. Este oferit gratuit un transfer dus-întors de la aerport sau port. Hotelul Poseidon oferă Wi-Fi gratuit în zonele publice şi parcare gratuită în incintă. Oaspeţii pot închiria iahtul cu motor al hotelului Poseidon pentru a descoperi plajele magnifice de pe insula Mykonos. În sala de mic dejun şi pe terasa sa răcoroasă, oaspeţii pot gusta delicatese locale de casă, fructe proaspete şi cafea de bună calitate. Alley Bay serveşte cocktail-uri exclusive la câţiva paşi de hotelul Poseidon. Hotelul Poseidon se află la numai 200 de metri de celebrele Mori de Vânt din Mykonos. Chiar lângă hotel, oaspeţii vor găsi mici golfuri de nisip şi o potecă ce duce la capela pitorească Charalambis Agios.','Poseidon Hotel Suites', 'FOUR_STARS', 4);

insert into hotel values (14, 'Semeli este un hotel sofisticat, situat în Mykonos, la 500 de metri de plaja Megali Ammos. Hotelul oferă unităţi de cazare decorate cu gust, cu vedere la mare, oraș sau grădină, o piscină încălzită cu apă dulce, cu șezlonguri, și un centru spa. Toate camerele şi suitele Hotelului Semeli au TV cu ecran plat, zonă de relaxare, baie de marmură şi uşi franceze cu vedere la mare. Zidurile albe şi grădina cu muşcate şi bougainvillea creează cadrul exterior al camerelor. Unele unităţi au cadă cu hidromasaj interioară sau în aer liber. Restaurantul à la carte Thioni oferă un mic dejun tip bufet bogat lângă piscină. Pe tot parcursul zilei sunt servite preparate culinare greceşti şi italiene în interior şi pe veranda cu vedere la mare sau la grădină. Barul de lângă piscina hotelului oferă cocktailuri. Oaspeţii pot folosi sala de gimnastică a Hotelului Semeli sau se pot relaxa la hamamul turcesc sau cu o şedinţă de masaj la centrul spa Semeli. Sunt disponibile diverse tratamente faciale şi corporale. Centrul oraşului Mykonos, unde se găsesc numeroase baruri, cafenele şi restaurante, este la câteva minute pe jos. În întregul hotel este disponibil WiFi gratuit, iar parcarea privată este gratuită.',  'Semeli Hotel', 'FIVE_STARS', 4);

insert into hotel values (15, 'Trend Suites CYCLE se află în Antalya, la 2,6 km de Acvariul din Antalya, şi oferă cazare cu aer condiționat și acces la o grădină. Proprietatea are cadă cu hidromasaj.Trend Suites CYCLE oferă acces la o terasă.Centrul comercial 5M Migros și parcul acvatic Aqualand din Antalya se află la 2,8 km de cazare. Cel mai apropiat aeroport este Aeroportul Antalya, situat la 16 km de Trend Suites CYCLE.','Trend Suites CYCLE', 'FOUR_STARS', 5);

insert into hotel values (16, 'Crowne Plaza Antalya se află lângă renumita plajă Konyaalti şi oferă unități de cazare luxoase, de 5 stele, cu vedere nelimitată la Marea Mediterană. Renovat în 2020, hotelul are piscine interioare și în aer liber, un centru spa extins și WiFi gratuit. Camerele au TV interactiv cu ecran plat și balcon cu vedere la mare. Unele camere luxoase de la Crowne Plaza includ o zonă de relaxare şi o cadă spa. Crowne Plaza Antalya găzduiește 3 restaurante care servesc mic dejun tip bufet şi mâncăruri turcești şi internaționale. Mesele pot fi savurate în interior sau pe terasă. Proprietatea acordă o importanță deosebită sănătății și bunăstării oaspeților. Centrul de fitness ultramodern este dotat cu aparate cardiovasculare şi greutăți. Ferestrele din podea până în tavan oferă vedere la orașul Antalya. Zeus Spa Centre are saună finlandeză și baie turcească și rusească. Crowne Plaza Antalya îndeplinește obligațiile legale cu privire la standardele de igienă. Personalul prietenos al biroului de relații cu clienții oferă asistență oaspeților pe durata șederii lor. Recepția este deschisă nonstop, asigurând servicii impecabile.', 'Crowne Plaza Antalya', 'FIVE_STARS', 5);

insert into hotel values (17, 'Situat în Istanbul, la 750 de metri de centrul comercial Cevahir, Hotelul Delita City oferă cazare cu restaurant, bar, grădină și parcare privată. Proprietatea se află la aproximativ 2,4 km de Palatul Dolmabahce și la 2,4 km de Piața Taksim și Turnul cu Ceas Dolmabahce. De asemenea, unitatea de cazare oferă recepție cu program nonstop, room-service și serviciu de schimb valutar. Toate unitățile de cazare au aer condiționat, TV cu ecran plat cu canale prin satelit, fierbător, duș, uscător de păr și birou. Fiecare cameră a hotelului include dulap și baie privată. Hotelul Delita City servește mic dejun continental sau tip bufet. Strada Istiklal este situată la 2,5 km de unitatea de cazare, iar Istanbul Sapphire se află la 3,3 km. Cel mai apropiat aeroport este Aeroportul Ataturk Istanbul, situat la 16 km de Hotelul Delita City. Proprietatea oferă serviciu de transfer de la/la aeroport, la un cost suplimentar.', 'Delita City Hotel ', 'FOUR_STARS', 6);

insert into hotel values (18, 'Overlooking the vibrant city skyline or Bosphorus, the hotel offers soundproofed rooms with free WiFi. The hotel has the Willow Stream Spa with a fully equipped gym, and indoor and seasonal outdoor pool, a diverse selection of restaurants, bars and a spa. A TV with satellite channels, wireless speaker as well as an iPad are offered. All rooms have a seating area, dining table and working desk for your convenience. All rooms have one touch button motorised curtains. Some rooms have a bath tub or rain shower, and some rooms have a heated Turkish bath in the bathroom. Suites and some rooms have private balconies overlooking the Bosphorus. Stations Restaurant offers breakfast and lunch, serving seasonal and fresh options prepared by chefs at live cooking stations. Daily breakfast is served as a rich open buffet featuring classic breakfast items, charcuterie varieties, egg stations, both traditional and international bakery selections among many others. Demlique by Tonka serves a rich choice of freshly made French pastries and handmade chocolate. Marble Bar is situated in the Fairmonts vibrant lobby for wine and spirits. Meditation, yoga, and fitness classes are available at the Willow Stream Spa. 24-hour front desk and concierge services are also available for your convenience. Fairmont Quasar Istanbul offers luxury airport transfer and meet&greet service at the airport upon request. This pet-friendly hotel also has a designated helipad area and offers helicopter transfer upon request. Istanbul Convention Centre is 3.5 km from Fairmont Quasar Istanbul while Cevahir Shopping Centre, Zorlu, Astoria and Profilo Shopping Centres are in a walking distance.','Fairmont Quasar Istanbul','FIVE_STARS',6);

insert into hotel values (19,'H10 Metropolitan se află în Barcelona, la 90 m de Plaça Catalunya, oferind terasă pe acoperiș, cu bar și piscină de relaxare. Pune la dispoziție un restaurant de tapas și WiFi gratuit. Fiecare cameră are TV cu ecran plat cu canale prin satelit, aer condiționat, aparat de cafea și minibar. Baia proprie oferă halate și uscător de păr. H10 Metropolitan se află la numai 2 minute de mers pe jos de bulevardul Paseo de Gracia, unde se găsesc buticuri și magazine de modă de designer. Hotelul este situat la 700 m de clădirea La Pedrera proiectată de Gaudi și la 3 minute de mers pe jos de bulevardul Las Ramblas. Sagrada Familia se află la aproximativ 10 minute de mers cu metroul.','H10 Metropolitan', 'FOUR_STARS',10);

insert into hotel values (20,'NH Collection Barcelona Gran Calderón este un hotel elegant cu o poziţie excelentă, chiar lângă bulevardul Passeig de Gràcia, în centrul oraşului Barcelona. Hotelul oferă un centru de fitness şi o piscină pe acoperiş, disponibilă gratuit pe tot parcursul anului, cu vedere spectaculoasă la oraş. Camerele hotelului NH Collection Barcelona Gran Calderón au aer condiţionat, WiFi gratuit, aparat de cafea Nespresso şi baie privată cu duş cu efect de ploaie şi uscător de păr profesional. Proprietatea asigură room service nonstop, iar barul Eleven serveşte cocktailuri şi gustări uşoare. Bufetul de mic dejun tip include o varietate de preparate cu un conţinut ridicat de antioxidanţi şi un colţ cu sucuri proaspete. Puteţi solicita micul dejun şi în cameră, iar proprietatea asigură un mic dejun matinal cu gustări uşoare. Personalul de la departamentul de relaţii cu oaspeţii oferă asistenţă pe tot parcursul sejurului, precum şi informaţii despre atracţiile şi activităţile disponibile în Barcelona. Hotelul se află la numai o stradă de renumita Casa Batlló, proiectată de Gaudí. Cartierul Gotic al oraşului este la aproximativ 10 minute de mers pe jos.','NH Collection','FIVE_STARS',10);
insert into hotel values (21,'Island Escape by Burasari oferă un restaurant, o piscină în aer liber, un bar și o grădină în orașul Phuket. Acest complex de 5 stele are WiFi gratuit, o zonă de plajă privată și un club al copiilor. La cazare există recepție cu program non-stop, room-service și schimb valutar pentru oaspeți.',
                          'Island Escape by Burasari - SHA Plus', "FIVE_STARS", 11);
insert into hotel values (22, 'Mai Morn Resort SHA Plus este situat în orașul Phuket, la 3,5 km de Casa Chinpracha și la 3,5 km de orașul vechi Phuket, cu piscină în aer liber, bar, grădină și WiFi gratuit. Proprietatea este situată la 3,5 km de Muzeul Thai Hua, la 2,4 km de Monumentul minier Saphan Hin și la 2,5 km de Complexul King Power Phuket. Hotelul are camere de familie',
                          ' Mai Morn Resort SHA Plus', "THREE_STARS", 11);
insert into hotel values (23, 'Oakwood Suites Bangkok se află în Bangkok și are restaurant, piscină în aer liber, centru de fitness și grădină. Acest hotel de 5 stele oferă WiFi gratuit, room-service și recepție cu program nonstop. Hotelul are camere de familie',
                          ' Oakwood Suites Bangkok - SHA Certified', 'FIVE_STARS', 12);
insert into hotel values (24, 'Conectat direct la stația BTS Skytrain Asok și la doar câțiva pași de stația de metrou MRT Sukhumvit, luxosul Sheraton Grande Sukhumvit oferă restaurante premiate și room service nonstop. De asemenea, are o piscină tropicală în aer liber și acces gratuit la internet WiFi în zonele publice. Toate camerele sunt dotate cu TV cu ecran plat și minibar bine aprovizionat, cu lenjerie de pat din bumbac de 300 de fire și dressing. Băile private au cadă și duș. Oaspeții se bucură de fructe de bun venit în camere. Sheraton Grande Sukhumvit, a Luxury Collection Hotel, Bangkok - Certificat SHA este situat vizavi de centrul comercial Terminal 21. Se află la aproximativ 2 km de magazinul universal Emporium și de magazinul universal Central Chidlom. Hotelul este la 3 km de magazinele de lux din Siam Paragon',
                          'Sheraton Grande Sukhumvit, a Luxury Collection Hotel, Bangkok - certificat SHA', 'FIVE_STARS', 12);
insert into hotel values (25, 'vând o baie publică, hotelul MONday Premium TOYOSU este situat convenabil în cartierul Koto Ward din Tokyo. Acest hotel de 4 starturi este situat în fața centrului comercial Aeon Shinonome, la 1,3 km de Urban Dock LaLaport Toyosu și la 2,5 km de Piața Toyosu. Printre facilitățile acestei proprietăți se numără un restaurant, o recepție deschisă nonstop și un serviciu gratuit de transfer, precum și WiFi gratuit. Parcarea privată este disponibilă la fața locului',
                          'Hotel Monday Premium TOYOSU', 'FOUR_STARS', 13);
insert into hotel values (26, 'Grand Nikko Tokyo Daiba este primul hotel Grand Nikko din Japonia, deschis de la 1 iulie 2016. Situată în zona Golfului Tokyo din Odaiba, această proprietate este cel mai apropiat hotel de stațiune urbană de centrul Tokyo, la 20 de minute de mers cu trenul și monorailul de Gara JR Tokyo. În întreaga proprietate este disponibil WiFi gratuit.Camerele spațioase ale acestui hotel au decor elegant în stil european și oferă acces gratuit la internet prin cablu în întreaga proprietate. Toate camerele includ TV cu ecran plat cu canale prin satelit, pernă cu pene și zonă de relaxare. Etajele superioare au vedere panoramică la Golful Tokyo, precum și vedere la Podul Curcubeu și Turnul Tokyo',
                          'Grand Nikko Tokyo Daiba', 'FIVE_STARS', 13);
insert into hotel values (27, 'Amplasat ideal în districtul Yodogawa Ward din Osaka, karaksa hotel grande Shin-Osaka Tower este situat la 400 de metri de TKP Garden City Shin Osaka, la 500 de metri de Arde! Shin-Osaka și la 700 de metri de Eki Marche Shin-Osaka. Având un restaurant, hotelul de 4 stele are camere cu aer condiționat și WiFi gratuit, fiecare cu baie privată. Unitatea de cazare are o recepție deschisă nonstop și un spațiu de depozitare a bagajelor pentru oaspeți',
                          'Karaksa hotel grande Shin-Osaka Tower', 'FOUR_STARS', 14);
insert into hotel values (28, 'Situat în Osaka, la 200 de metri de Altarul Namba, Osaka Excel Hotel Tokyu oferă unități de cazare cu restaurant, parcare privată, centru de fitness și bar. La aproximativ 500 de metri de Centrul de conferințe TKP Shinsaibashi Ekimae, proprietatea este, de asemenea, la numai 64 de metri de Templul Nanba Betsuin și oferă WiFi gratuit. Unitatea de cazare oferă o recepție cu program nonstop, depozit de bagaje și schimb valutar pentru oaspeți',
                          'Osaka Excel Hotel Tokyu', 'FOUR_STARS', 14);
insert into hotel values (29, 'Beneficiind de o locație ideală pe insula Sentosa din Singapore, Village Hotel Sentosa by Far East Hospitality se află la 600 de metri de Wings Of Time, la mai puțin de 1 km de parcul acvatic Adventure Cove și la 2 km de S.E.A. Acvariu. Acest hotel de 4 stele pune la dispoziție un centru de fitness şi camere cu aer condiționat, acces gratuit la internet WiFi şi baie privată. De asemenea, există o recepție cu program nonstop, room service și schimb valutar',
                          'Village Hotel Sentosa by Far East Hospitality', 'FOUR_STARS', 15);
insert into hotel values (30, 'Hotelul de 5 stele Pan Pacific Singapore oferă acces direct la centrul comercial Marina Square și Centrul de convenții Suntec. Hotelul este situat la intrarea în cartierele de afaceri și financiare din Singapore și are o piscină în aer liber, un bar și 6 localuri în care oaspeții pot lua masa. Oaspeții beneficiază de acces WiFi gratuit în întreaga proprietate',
                          'Hotel Pan Pacific Singapore', 'FIVE_STARS', 15);
insert into hotel values (31, 'Baros Maldives se află pe o insulă mică, aproape de orașul Male, într-o lagună cu apă turcoaz, şi oferă vile retrase, la umbra palmierilor, lângă o plajă cu nisip alb, sau amplasate deasupra apei, cu terasă privată la soare. Multe dintre vilele elegante, cu gresie, lemn și acoperiș din palmieri au piscină de relaxare privată, iar unele au și cadă spa. Toate vilele sunt private şi includ aparat de cafea espresso, minibar și vin. Printre facilitățile de divertisment din vilă se numără TV cu ecran plat și stație de andocare pentru iPod. Oaspeții se pot răsfăța la spa sau pot face o baie în piscina infinită, situată deasupra apei. În plus, aceștia pot practica sporturi de apă și yoga. Complexul oferă un lounge cu bibliotecă și acces gratuit la internet WiFi în camere',
                          'Baros Maldives', 'FIVE_STARS', 16);
insert into hotel values (32, 'EN Maldives Malé by Shangri-La are o piscină infinită pe acoperiș, cu vedere la Oceanul Indian şi oferă un serviciu gratuit de transfer dus-întors la/de la Aeroportul Internațional Velana, situat la 7 minute de mers cu mașina. Hotelul are un centru spa și o cafenea deschisă nonstop. Cardurile Union Pay sunt acceptate ca modalitate de plată. JEN Maldives Malé by Shangri-La Maldives se află în cartierul de afaceri din Malé, la 10 - 12 minute de mers pe jos de piața de pește a insulei și de Rasrani Bageecha.',
                          'Jen Maldives Male by Shangri-La', 'FOUR_STARS', 16);
insert into hotel values (33, 'Riu Plaza Manhattan Times Square se află în New York, la 300 m de Times Square și Radio City Music Hall și oferă un bar și o terasă. Există diverse facilități, precum un restaurant, recepție cu program non-stop, un serviciu de concierge și WiFi gratuit în întreaga proprietate. Hotelul are camere de familie.',
                          'Riu Plaza Manhattan Times Square', 'FOUR_STARS', 17);
insert into hotel values (34, 'Acest hotel de 5 stele este situat în centrul cartierului Manhattan, la numai 10 minute de mers pe jos de Times Square. Hotelul este elegant și oferă un restaurant și sală de gimnastică. Facilitățile din camere includ frigider. Toate camerele Hotelului InterContinental New York Barclay au iPod docking station şi TV prin cablu cu DVD player. Pun, de asemenea, la dispoziție minibar şi facilităţi de ceai/cafea. Camerele sunt decorate în nuanțe aurii.',
                          ' InterContinental New York Barclay Hotel, an IHG Hotel', 'FIVE_STARS', 17);
insert into hotel values (35, 'Cu 4 piscine, un restaurant şi un centru de fitness deschis nonstop, EAST Miami oferă câte ceva pentru fiecare. Situat în centrul cartierului Brickell, EAST Miami asigură magazine premium, un cinematograf, restaurante şi baruri, centre spa şi multe altele. Camerele şi suitele au decor elegant cu accesorii moderne, inclusiv ferestre din podea până în tavan, duş cu efect de ploaie şi acces gratuit la internet WiFi pentru oaspeţi. Fiecare unitate oferă un balcon spaţios, o baie privată şi facilităţi de ceai şi cafea. Toate camerele au TV cu ecran plat de 50 inch.',
                          'EAST Miami', 'FIVE_STARS', 18);
insert into hotel values (36, 'Acest Hampton Inn, situat în centrul orașului Miami se află la 1 minut de mers pe jos de stația de metrou Brickell. Are piscină în aer liber și WiFi gratuit. În fiecare zi se oferă un mic dejun cu preparate calde.',
                          'Hampton Inn & Suites by Hilton Miami Downtown/Brickell', 'FOUR_STARS', 18);
insert into hotel values (37, 'Acest hotel mare de 4 stele pune la dispoziţie unităţi de cazare luxoase, bine amenajate, dintre care unele cu vedere la Lacul Ontario și la orizontul spectaculos al orașului Toronto. Oaspeții au la dispoziție o piscină interioară, un centru de fitness şi terenuri de tenis situate pe acoperiș.',
                          'The Westin Harbour Castle, Toronto', 'FOUR_STARS', 19);
insert into hotel values (38, 'Construit în 1914, acest hotel din centrul orașului Toronto îmbină farmecul istoric și eleganța cu facilități moderne. Piața St Lawrence și Hockey Hall of Fame sunt la mai puțin de 10 minute de mers pe jos. Unitățile de cazare de la acest hotel de suite sunt dotate cu o varietate de facilități, inclusiv cuptoare cu microunde, frigidere și cafetiere. De asemenea, acestea includ zone separate de dormit, de luat masa și de lucru. One King West Hotel and Residence are un centru de fitness, împreună cu un restaurant și un bar.',
                          'One King West Hotel and Residence', 'FOUR_STARS', 19);
insert into hotel values (39, 'Oferind un restaurant şi o piscină interioară pe acoperiş, acest hotel din lanţul Hilton este situat la 3 minute de mers pe jos de staţia de metrou Place-des-Arts. Asigură camere spaţioase, cu acces gratuit la internet WiFi. Toate camerele moderne ale hotelului Hilton Garden Inn Montreal includ un TV cu ecran plat cu ecran plat de 32 inch cu HBO. Fiecare cameră are cuptor cu microunde, frigider şi aparat de cafea. De asemenea, există un birou şi un scaun.',
                          'Hilton Garden Inn Montreal Centre-Ville', 'FOUR_STARS', 20);
insert into hotel values (40, 'Hotelul Le Cantlie Suites este situat în centrul orașului, chiar lângă Universitatea McGill. Proprietatea are o piscină şi oferă acces WiFi.  Camerele spațioase ale Hotelului Le Cantlie Suites au bucătărie în stil european, utilată cu frigider şi cuptor cu microunde. Oaspeții Hotelului Le Cantlie se pot antrena în sala de gimnastică şi pot afla informații despre punctele de atracție și evenimentele din zonă prin intermediul serviciului de concierge.',
                          'Hôtel Le Cantlie Suites', 'FOUR_STARS', 20);
insert into hotel values (41, 'Situat în Cancún, la 16 km de Autogara Cancún, Riu Palace Costa Mujeres - All Inclusive oferă cazare cu piscină în aer liber, centru de fitness, bar și parcare privată gratuită. Facilitățile includ recepție cu program non-stop, room service și acces gratuit la internet WiFi în toate zonele proprietății. Oaspeții se pot distra la parcul acvatic, pot savura o băutură sau se pot relaxa într-un lounge comun.',
                          'Riu Palace Costa Mujeres - All Inclusive', 'FIVE_STARS', 21);
insert into hotel values (42, 'Situat în Cancún, la 2,5 km de plaja Mujeres, Planet Hollywood Adult Scene Cancun Resort & Spa - All Inclusive oferă cazare cu un restaurant, parcare privată gratuită, o piscină în aer liber și un centru de fitness. Printre facilitățile acestei proprietăți se numără o recepție deschisă nonstop și room service, precum și WiFi gratuit în întreaga proprietate. Oaspeții pot savura o băutură la bar.',
                          'Planet Hollywood Adult Scene Cancun, An Autograph Collection All-Inclusive Resort', 'FIVE_STARS', 21);
insert into hotel values (43, 'Situat lângă stația de metrou Hidalgo, Hotelul Fontan Reforma oferă WiFi gratuit în întreaga proprietate, sistem de încălzire şi camere cu aer condiționat și TV prin satelit. Proprietatea este la câțiva pași de centrul istoric al orașului, de parcul Alameda și de Colonial Art Gallery. Hotelul Fontan are un restaurant care oferă un bufet de prânz și un meniu à la carte pentru cină. La doar câteva minute de Fontan Reforma se găsesc mai multe restaurante și lounge-uri. Palatul Artelor Frumoase și Muzeul Franz Mayer sunt la aproximativ 3 străzi de hotel. Cuplurile apreciază în mod deosebit această locaţie. I-au dat scorul 9,3 pentru un sejur pentru 2 persoane.',
                          ' Hotel Fontan Reforma', 'FOUR_STARS', 22);
insert into hotel values (44, 'Amplasat în faţa cercului Cristofor Columb din cartierul cultural, de afaceri şi financiar al oraşului Ciudad de México, acest hotel oferă servicii de lux, cum ar fi un spa în incintă, precum şi opţiuni culinare delicioase. Fiesta Americana Reforma are facilităţi luxoase pentru un sejur relaxant. Puteţi beneficia de un masaj la spa sau puteţi face mişcare la sala de sport ultramodernă, în timp ce copiii participă la activităţile din cadrul programului Fiesta Kids.',
                          'Fiesta Americana Reforma', 'FIVE_STARS', 22);
insert into hotel values (45, 'Hotelul Atlantico Tower oferă unități de cazare moderne în centrul oraşului Rio de Janeiro, la 600 de metri de Museu do Amanhã şi la 1,5 km de Aeroportul Santos Dumont. Acesta are WiFi gratuit și piscină pe acoperiș cu vedere panoramică la oraș. Camerele Hotelului Atlantico Tower au interior simplu, cu mobilier frumos din lemn şi podea cu gresie de culoare deschisă. Toate camerele au aer condiționat, minibar şi birou pentru laptop. Zilnic se oferă un mic dejun tip bufet.',
                          'Hotel Atlantico Tower', 'FOUR_STARS', 23);
insert into hotel values (46, 'Hotelul Américas Granada are un restaurant, o piscină în aer liber, un centru de fitness și un bar în Rio de Janeiro. Printre facilitățile acestei proprietăți se numără o recepție deschisă nonstop și room service, precum și WiFi gratuit în întreaga proprietate. Parcarea privată poate fi aranjată la un cost suplimentar.',
                          'Hotelul Americas Granada', 'FOUR_STARS', 23);
insert into hotel values (47, 'Situat convenabil în cartierul Pinheiros, Mercure São Paulo Pinheiros oferă o sală de sport. Hotelul Mercure este situat aproape de strada Oscar Freire, Centrul de Convenții Rebouças și faimosul cartier Vila Madalena. Este disponibil acces gratuit la internet WiFi. Restaurantul La Terrina al hotelului servește mâncăruri italiene gătite cu ingrediente de sezon. Mercure São Paulo Pinheiros are, de asemenea, un bar confortabil, care oferă cocktailuri, gustări și muzică live, precum și o grădină fermecătoare. Micul dejun este servit zilnic.',
                          'Mercure Sao Paulo Pinheiros', 'FOUR_STARS', 24);
insert into hotel values (48, 'Hotelul Maksoud Plaza Distributed by Accorhotels este situat în inima orașului Sao Paulo și este situat ideal, la 260 de metri de faimosul Bulevar Paulista. Proprietatea se află la doar 15 minute de mers cu mașina de Aeroportul Intern Congonhas din Sao Paulo.În mijlocul fântânilor liniștitoare și amenajării teritoriului din holul Atrium, restaurantul informal "150 Maksoud" servește micul dejun. Hotelul Maksoud Plaza Distribuit de Frank Bar de la Accorhotels a câștigat cel mai bun barman și cel mai bun meniu de băuturi de către Veja Comer e Beber, barul oferă o listă de 33 de băuturi.',
                          'Hotel Maksoud Plaza Distribuit de Accorhotels', 'FOUR_STARS', 24);
insert into hotel values (49, 'Situat în cartierul elegant Puerto Madero, Hilton Buenos Aires oferă unități de cazare luxoase, cu vedere la oraș și la râu. Hotelul are facilități de spa, un centru de fitness, o piscină pe acoperiș și se mândrește cu un hol iconic și impresionant cu atrium din sticlă. Oaspeții de la Hilton Buenos Aires se pot bucura de camere confortabile și spațioase, cu mochetă, cu decor clasic și facilități moderne. Camerele Executive oferă acces exclusiv la Executive Lounge. La fața locului sunt oferite trei concepte gastronomice elegante. Oaspeții se pot delecta cu mâncăruri internaționale la restaurantul El Faro, pot bea un cocktail sau două la barul Alberto`s Lobby sau pot gusta cafea regională la Croutons grab and go.',
                          'Hilton Buenos Aires', 'FIVE_STARS', 25);
insert into hotel values (50, 'Claridge este un hotel de lux amplasat într-o clădire neoclasică din centrul orașului Buenos Aires, la doar 400 de metri de bulevardul 9 de Julio. Facilitățile oferite includ opțiuni rafinate de luat masa, precum și acces la o serie de expoziții de pictură, evenimente culturale și recitaluri de operă. În timpul verii, oaspeții au la dispoziție o sală de fitness şi o piscină. Camerele elegante ale Hotelului Claridge au interior clasic și ferestre franceze mari. Toate oferă aer condiționat, TV cu ecran plat și canale prin cablu și WiFi gratuit.',
                          'Claridge Hotel', 'FIVE_STARS', 25);
insert into hotel values (51, 'Hotelul Elegance oferă unități de cazare moderne, cu acces gratuit la internet WiFi în toate zonele, la doar 2 străzi de Plaja Grande și Complexul Normandina. Este situat la o stradă de bulevardul Alem, cu numeroasele sale restaurante, magazine și viața de noapte. Toate camerele Hotelului Elegance au aer condiționat și încălzire, precum și minibar. Au ferestre mari cu vedere la oraș și vedere parțială la mare. De asemenea, camerele au TV prin cablu și WiFi gratuit.',
                          ' Hotel Elegance', 'FOUR_STARS', 26);
insert into hotel values (52, 'La doar 500 de metri de plaja La Perla, Hotelul Nuevo Ostende oferă camere decorate cu gust, cu Wi-Fi gratuit. Piața San Martin și târgul său de meșteșuguri pitoresc de weekend sunt la 50 de metri de hotel. Camerele Hotelului Nuevo Ostende sunt amenajate într-o paletă de măsline verzi și au podea cu parchet. Acestea au TV prin cablu și baie privată. Oaspeții se pot trezi cu un mic dejun complet cu sucuri proaspete și croissante, pe care îl pot savura în curtea centrală fermecătoare sau în restaurant.',
                          'Hotel New Ostende', 'THREE_STARS', 26);
insert into hotel values (53, 'Situat în Santiago, la 1,2 km de Muzeul Memoriei Santiago, Hotelul Brasilia oferă cazare cu un bar, parcare privată gratuită și un lounge comun. Printre facilitățile acestei proprietăți se numără un centru de afaceri și un serviciu de concierge, precum și WiFi gratuit în întreaga proprietate. Unitatea de cazare oferă o recepție deschisă nonstop, room service și schimb valutar pentru oaspeți. Toate camerele hotelului au aer condiționat, zonă de relaxare, TV cu ecran plat cu canale prin satelit, cutie de valori și baie privată cu duș, uscător de păr și articole de toaletă gratuite. La Hotelul Brasilia toate camerele sunt dotate cu lenjerie de pat și prosoape. Unitatea de cazare oferă un mic dejun continental sau à la carte.',
                          'Hotel Brasilia', 'THREE_STARS', 27);
insert into hotel values (54, 'Situat în cartierul tradițional Paris-Londra din centrul orașului Santiago, acest hotel oferă cazare de 4 stele, cu TV prin cablu și Wi-Fi gratuit. Oaspeții se bucură de un restaurant, o sală de gimnastică și o unitate de saună. Unitățile de cazare de la Hotelul Fundador sunt dotate cu minibar și cutie de valori. Se oferă room service nonstop. Accesul la internet este disponibil contra cost. Restaurantul Calicanto servește preparate din bucătăria mediteraneană. Oaspeții pot încerca, de asemenea, un meniu de vinuri bazat pe opțiuni locale.',
                          'Fondatorul hotelului', 'FOUR_STARS', 27);
insert into hotel values (55, 'Printre diversele servicii oferite de hotel oaspeții vor găsi săli de conferințe, WiFi gratuit în întreaga proprietate, servicii de curățătorie chimică, centru de fitness și piscină în aer liber. De asemenea, un mic dejun tip bufet gratuit este servit zilnic. Camerele de la Diego de Almagro Costanera au aer condiționat, TV LCD cu canale prin cablu și birou. Camerele oferă vedere la oraș sau la ocean. Restaurantul proprietății servește mâncăruri regionale și internaționale, însoțite de o selecție largă de vinuri chiliane. Oaspeții vor găsi, de asemenea, parcare gratuită la fața locului (în funcție de disponibilitate).',
                          'Hotel Diego De Almagro Costanera - Antofagasta', 'FOUR_STARS', 28);
insert into hotel values (56, 'Situat pe coasta NH Antofagasta oferă cazare în zona de sud a orașului Antofagasta. Hotelul are vedere frumoasă la ocean, o piscină în aer liber, un centru de fitness modern și WiFi gratuit. Camerele sunt decorate în tonuri calde, cu finisaje din lemn. Toate camerele au vedere la ocean și la oraș, TV LCD prin satelit, aer condiționat și minibar, precum și room service, disponibil între orele 11:00 și 23:00. Micul dejun tip bufet este servit zilnic la restaurantul proprietății. În plus, oaspeții se pot bucura de un meniu à la carte cu preparate din bucătăria internațională și chiliană. De asemenea, oaspeții pot savura un Pisco Sour la barul cu vedere la Oceanul Pacific.',
                          'NH Antofagasta', 'FOUR_STARS', 28);

insert into hotel values (57, 'Complexul all-inclusive Albatros Citadel Resort - Families and couples only oferă camere cu vedere panoramică la Marea Roşie şi 3 piscine, inclusiv o piscină infinită uimitoare. Hotelul pune la dispoziţie 6 căzi private cu hidromasaj şi un centru de fitness ultramodern. Complexul este construit din pietre naturale din coral care au fost lucrate manual din munţii din apropiere. Toate camerele sunt spaţioase şi au facilităţi de lux şi vedere spectaculoasă la mare. Camerele sunt frumos amenajate şi includ TV cu ecran plat şi minibar. Fiecare oferă birou şi aer condiţionat. Accesul la internet prin cablu este gratuit în toate camerele.',
                          'Albatros Citadel Resort', 'FIVE_STARS', 29);
insert into hotel values (58, 'Acest hotel all inclusive este situat pe plaja de la Marea Roşie, la doar 3 km de centrul oraşului Hurghada. Acesta oferă piscine cu apă dulce care se întind pe o suprafaţă de 800 mp, precum şi camere cu minibar gratuit şi balcon. Oaspeţii pot lua cina la lumina lumânărilor în localul Bordiehns, care serveşte preparate culinare din bucătăria orientală de tip fusion. De asemenea, există 1 bar la piscină, oferind o selecţie de sortimente de îngheţată, şi alte 5 baruri care servesc gustări uşoare şi băuturi. Camerele moderne de la Bel Air Azur Resort au vedere la zona piscinei centrale. Toate sunt dotate cu TV prin satelit, uscător de păr şi măsuţă de cafea cu scaune de răchită.',
                          'Bel Air Azur Resort (Adults Only)', 'FOUR_STARS', 29);
insert into hotel values (59, 'Complexul Albatros are o zonă de piscină în aer liber cu vedere la plajele aurii din golful Nabq. Oferă camere spaţioase, cu balcon privat mobilat. Proprietatea asigură parcare privată gratuită. Oaspeţii complexului Royal Albatros Moderna - Families and couples only sunt cazaţi în camere luminoase şi moderne, amenajate cu o zonă de relaxare şi ferestre mari care se deschid spre balcon. Camerele au baie privată cu facilităţi moderne de duş. Oaspeţii se pot relaxa pe unul dintre şezlongurile de lângă piscină şi pot savura o băutură rece sub soarele egiptean. Recepţia hotelului este deschisă nonstop şi asigură asistenţă pentru organizarea de activităţi în zonă, acestea incluzând scufundări, ciclism sau închiriere de scutere.',
                          'Royal Albatros Moderna - Families and couples only', 'FIVE_STARS', 30);
insert into hotel values (60, 'Steigenberger Alcazar este cel mai nou complex din Nabq, situat la aproximativ 15 minute de Aeroportul Internațional Sharm El-Sheikh. Acest complex de 5 stele are o zonă privată de 30.000 m2 cu peisaj subacvatic, precum și 3 piscine care sunt încălzite iarna. Oaspeții beneficiază de WiFi gratuit în întreaga proprietate și în camere. Steigenberger Alcazar oferă 610 de camere. Camerele superioare și camerele de familie Deluxe se află chiar lângă plajă, iar în vile și în suitele Junior pot fi cazate grupuri mai mari. Alcazar are 2 restaurante principale care servesc micul dejun, prânzul și cina, precum și 5 restaurante à la carte cu specializări diferite. În plus, există 2 baruri în hol, baruri la piscină și un bar pe plajă.',
                          'Steigenberger Alcazar', 'FIVE_STARS', 30);
insert into hotel values (61, 'Iberostar Selection Kuriat Palace se află la malul mării, în orașul Monastir şi are o zonă de plajă privată. Printre diferite facilități oferite de hotel se numără o piscină în aer liber și un centru de wellness şi spa. Oaspeții au la dispoziție cadă cu hidromasaj, personal de divertisment şi recepţie cu program nonstop. Camerele de la Iberostar Selection Kuriat Palace sunt prevăzute cu birou, TV cu ecran plat și baie privată, dotată cu duș, iar unele camere includ o zonă de relaxare. În toate unitățile de cazare există un dulap. Hotelul serveşte un mic dejun tip bufet în fiecare dimineață. Restaurantul hotelului oferă o gamă variată de preparate internaționale şi opțiuni fără gluten. Hotelul are și saună.',
                          'Iberostar Selection Kuriat Palace', 'FIVE_STARS', 31);

insert into hotel values (62, 'Regency Hotel, Spa se află în oraşul Monastir, la 5 minute de mers pe jos de centrul localității. Oferă vedere la plajă și are piscină atât interioară, cât și în aer liber, centru de balneoterapie și terasă la soare. Regency Hotel Spa îmbină designul modern cu elementele tradiţionale tunisiene. Fiecare dintre camere este spaţioasă şi are TV prin satelit, minibar, baie privată şi balcon. Micul dejun este oferit zilnic. Restaurantul oferă preparate locale şi internaţionale, care pot fi savurate în zona de luat masa sau pe terasă.',
R_STARS', 31);
insert into hotel values (63, 'Situat în Tunis, pe renumitul bulevard Habib Bourguiba, Hotelul Africa Tunis se află la 15 minute de mers cu mașina de Aeroportul Tunis-Carthage. Acesta pune la dispoziție camere izolate fonic, cu aer condiționat și vedere frumoasă la oraș. Restaurantul Hotelului Africa Tunis, Kilimandjaro, servește mâncăruri din bucătăria mediteraneană. Oaspeții se pot relaxa la barul din hol. De asemenea, hotelul are braserie pe terasă, cu vedere la Avenue de Tunis. Africa oferă recepție deschisă nonstop, ziare gratuite, schimb valutar și serviciul de închirieri auto.',
                          ' El Mouradi Hotel Africa Tunis', 'FIVE_STARS', 32);
insert into hotel values (64, 'Situat în Tunis, la câțiva pași de Piața Victoriei și la câțiva pași de Bab El Bhar - Porte de France, Royal Victoria oferă cazare cu terasă și parcare privată gratuită pentru oaspeții care conduc. Oferind un lounge comun, hotelul de 4 stele oferă camere cu aer condiționat și WiFi gratuit, fiecare cu baie privată. Unitatea de cazare oferă o recepție cu program nonstop, room service și schimb valutar pentru oaspeți. Toate camerele hotelului sunt dotate cu TV cu ecran plat cu canale prin satelit și cutie de valori. Unitățile au dulap. Royal Victoria oferă un bufet sau un mic dejun complet englezesc / irlandez.',
                          ' Royal Victoria', 'FOUR_STARS', 32);
insert into hotel values (65, 'ferind vedere frumoasă la Oceanul Indian, Hotelul Parade oferă cazare la prețuri accesibile. Situat lângă plaja din Durban, se află la câțiva pași de Sun Coast Casino, Stadionul Moses Mabida, Stadionul Kings Park și Stadionul Kingsmead. Camerele Hotelului Parade sunt mobilate confortabil și au dimensiuni diferite. Fiecare este dotată cu TV prin satelit și seif. Majoritatea camerelor au ventilator de tavan. Este disponibil WiFi gratuit. De asemenea, oaspeții se pot bucura de un mic dejun englezesc gratuit aici.',
                          'Hotel Parade',
                          'Regency Hotel & Spa', 'FOU'THREE_STARS', 33);
insert into hotel values (66, 'Hotelul Blue Waters se află vizavi de faimoasa plajă din Durban, fiind la câţiva paşi de Cazinoul Suncoast şi de faimosul stadion Moses Mabhida. Atât UshaKa Marine World, cât şi terenul de curse Greyville se află la mai puţin de 4 km de hotel. Camerele şi suitele spaţioase sunt dotate cu TV LCD şi facilităţi pentru prepararea de ceai şi cafea. Fiecare cameră are aer condiţionat şi birou. Hotelul are un spațiu pentru depozitarea de bagaje. Majoritatea camerelor au balcon mobilat şi vedere la Oceanul Indian. Oaspeții de la Blue Waters pot savura ceai de după-amiaza și prăjituri în Florida Lounge cu vedere la ocean. Restaurantul Versailles oferă mese tip bufet şi à la carte pentru prânz şi cină. Facilitățile de agrement de la Hotelul Blue Waters includ o piscină interioară, o saună și un teren de squash. De asemenea, există o piscină în aer liber pe acoperiș, iar oaspeții pot savura băuturi cu vedere la apusul de soare de la barul de pe acoperiș.',
                          ' Blue Waters Hotel', 'FOUR_STARS', 33);

insert into hotel values (67, 'Având acces direct la plajă și o piscină încălzită cu energie solară, Bliss Boutique Hotel oferă cazare în Cape Town. Hotelul are o terasă la soare și vedere neîntreruptă la Muntele Table, Insula Robben și Oceanul Atlantic. În întreaga proprietate este disponibil WiFi gratuit. Camerele sunt dotate cu aer condiționat, TV cu ecran plat și aparat Nespresso. Unele unități au zonă de relaxare pentru confortul dumneavoastră, iar unele camere au terasă sau balcon. Toate camerele au baie privată, precum și halate de baie și papuci. Restaurantul hotelului oferă micul dejun, prânzul și cina, iar oaspeții pot savura o băutură la bar. Proprietatea are recepție cu program nonstop și parcare privată gratuită.',
                          'Bliss Boutique Hotel', 'FOUR_STARS', 34);
insert into hotel values (68, 'Radisson Blu Hotel Waterfront are vedere la faimoasa insulă Robben din Cape Town şi la Oceanul Atlantic. Pune la dispoziție unităţi de cazare luxoase, cu acces gratuit la internet wireless şi un port de agrement privat. Oaspeții beneficiază de WiFi gratuit în toată proprietatea. Radisson Blu Hotel Waterfront este aproape de principalele atracţii turistice şi plaje din Cape Town şi la câţiva paşi de Victoria & Alfred Waterfront. Hotelul are o varietate de camere moderne, pentru a satisface nevoile tuturor turiștilor.',
 'Radisson Blu Hotel Waterfront', 'FIVE_STARS', 34);
insert into hotel values (69, 'Oferind o piscină în aer liber, Eden Lodges este situat în Marrakech. Este disponibil acces gratuit la internet WiFi. Fiecare cameră de aici oferă aer condiționat, minibar și zonă de relaxare. Baia privată are duș, uscător de păr și halate de baie. Vă puteți bucura de vedere la grădină din cameră. Facilitățile suplimentare includ o zonă de relaxare în aer liber, o cutie de valori și lenjerie de pat. La Eden Lodges veți găsi, de asemenea, un jacuzzi cu balneoterapie încălzit, care poate conține până la 20 de persoaneo  minunată grădină tropicală. Alte facilități oferite la proprietate includ un lounge comun. Proprietatea oferă parcare gratuită și Wifi High debit, Hotelul se află la 3,9 km de Medersa Ben Youssef, la 10 km de Muzeul Marrakech și la 6,4 km de Grădinile Majorelle. Aeroportul Marrakech-Menara este la 12 km.',
                          'Eden Lodges', 'FIVE_STARS', 35);
insert into hotel values (70, 'Riad Jemaa El Fna & Spa se află în Marrakech şi oferă o piscină în aer liber şi WiFi gratuit. Facilităţile includ o grădină, o terasă şi un bar. Djemaa El Fna este la 2 minute de mers pe jos, iar Bazarul din Medina este la 300 de metri de Riad. Camerele acestui riad au un patio. Camerele includ o baie privată, iar unele unităţi de la Riad Jemaa El Fna & Spa se bucură şi de o zonă de relaxare.  Proprietatea serveşte un mic dejun continental. Proprietatea găzduieşte un restaurant care oferă preparate din bucătăria marocană şi internaţională. Puteţi solicita şi opţiuni halal.',
                          'Riad Jemaa El Fna & Spa', 'FOUR_STARS', 35);
insert into hotel values (71, 'Unitățile de cazare sunt dotate cu aer condiționat și TV cu ecran plat cu canale prin satelit, chicinetă complet utilată, cu zonă de luat masa, și baie privată cu uscător de păr. De asemenea, există cuptor cu microunde, frigider și minibar, precum și fierbător. Micul dejun à la carte este disponibil zilnic la hotelul de apartamente. Hotelul BH Appart oferă o terasă.',
                          'BH Appart Hotel', 'FOUR_STARS', 36);
insert into hotel values (72, 'Acest hotel situat la 6 km de moscheea Hassan II și centrul comercial Morocco Mall pune la dispoziţie o piscină, un centru de fitness și un centru spa. Hotelul are grădini cu plante tropicale și oferă vedere la mare şi la La Corniche, promenada de pe malul mării.  Fiecare cameră, suită și bungalou include balcon cu vedere la mare, la piscina în aer liber sau la grădină. Unităţile de cazare includ aer condiționat, TV cu ecran plat, Wi-Fi gratuit și baie proprie. Oaspeții pot savura mâncăruri din bucătăria marocană sau internațională în oricare dintre cele 3 restaurante, care oferă şi meniuri pentru diete speciale. În fiecare dimineaţă este servit un bufet de mic dejun. Aveţi la dispoziţie și 2 baruri în care vă puteți petrece serile. De asemenea, hotelul oferă Wi-Fi gratuit în toate zonele publice.',

                          'Casablanca Le Lido Thalasso & Spa (ex Riad Salam)', 'FOUR_STARS', 36);

INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (2,'2021-10-30 00:00:00.000000','2021-11-29 00:00:00.000000','Hotel Rainer',1,125,60,125,'FOUR_STARS',4,'INDIVIDUAL','STANDARD_ROOM','BED_AND_BREAKFAST',2,2,1,1,4);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (3,'2021-10-30 00:00:00.000000','2021-10-29 00:00:00.000000','Grand Hotel',1,125,50,125,'FOUR_STARS',3,'INDIVIDUAL','STANDARD_ROOM','HALF_BOARD',2,2,1,1,6);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (4,'2021-11-08 00:00:00.000000','2021-11-07 00:00:00.000000','Ramada by Wyndham Constanta',1,156,70,156,'FIVE_STARS',10,'INDIVIDUAL','STANDARD_ROOM','HALF_BOARD',1,1,1,1,1);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (5,'2021-11-17 00:00:00.000000','2021-11-16 00:00:00.000000','New Royal',1,97.5,45,97.5,'FOUR_STARS',7,'INDIVIDUAL','DOUBLE_ROOM_SEA_VIEW','HALF_BOARD',1,1,1,1,2);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (6,'2022-06-10 00:00:00.000000','2022-06-09 00:00:00.000000','Poseidon Hotel Suites',1,200,75,200,'FOUR_STARS',8,'AVION','DOUBLE_ROOM_SEA_VIEW','ALL_INCLUSIVE',4,4,1,2,13);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (7,'2022-08-20 00:00:00.000000','2022-08-19 00:00:00.000000','Semeli Hotel',1,200,75,200,'FIVE_STARS',6,'AVION','DOUBLE_ROOM_GARDEN_VIEW','ULTRA_ALL_INCLUSIVE',4,4,1,2,14);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (8,'2022-04-08 00:00:00.000000','2022-04-07 00:00:00.000000','Athens Gate Hotel',1,175,80,175,'FOUR_STARS',9,'AVION','SUITE','FULL_BOARD',3,3,1,2,11);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (9,'2022-09-16 00:00:00.000000','2022-09-15 00:00:00.000000','Royalty Hotel Athens',1,125,50,125,'FOUR_STARS',8,'AVION','STANDARD_ROOM','FULL_BOARD',3,3,1,2,12);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (10,'2022-04-07 00:00:00.000000','2022-04-06 00:00:00.000000','HP Tower One',1,150,75,150,'FOUR_STARS',3,'INDIVIDUAL','STANDARD_ROOM','HALF_BOARD',2,2,1,1,5);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (11,'2022-07-08 00:00:00.000000','2022-07-07 00:00:00.000000','Mirage Medspa Hotel',1,120,60,120,'THREE_STARS',6,'INDIVIDUAL','DOUBLE_ROOM_SEA_VIEW','FULL_BOARD',1,1,1,1,3);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (12,'2022-08-19 00:00:00.000000','2022-08-18 00:00:00.000000','Trend Suites Cycle',1,130,60,130,'FOUR_STARS',5,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',5,5,1,3,15);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (13,'2022-08-11 00:00:00.000000','2022-08-10 00:00:00.000000','Crowne Plaza Antalya',1,120,50,120,'FIVE_STARS',2,'INDIVIDUAL','SUITE','ALL_INCLUSIVE',5,5,1,3,16);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (14,'2022-05-20 00:00:00.000000','2022-05-19 00:00:00.000000','Delita City Hotel',1,100,45,100,'FOUR_STARS',9,'AVION','STANDARD_ROOM','FULL_BOARD',6,6,1,3,17);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (15,'2022-06-13 00:00:00.000000','2022-06-12 00:00:00.000000','Fairmont Quasar Istambul',1,150,80,150,'FIVE_STARS',7,'AVION','DOUBLE_ROOM_GARDEN_VIEW','FULL_BOARD',6,6,1,3,18);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (16,'2022-03-06 00:00:00.000000','2022-03-05 00:00:00.000000','Hotel Giolli Nazionale',1,80,35,80,'THREE_STARS',9,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',7,7,1,4,7);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (17,'2022-04-03 00:00:00.000000','2022-04-02 00:00:00.000000','Smooth Hotel Rome West',1,130,50,130,'FOUR_STARS',4,'AVION','DOUBLE_ROOM_GARDEN_VIEW','HALF_BOARD',7,7,1,4,8);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (18,'2022-05-03 00:00:00.000000','2022-05-02 00:00:00.000000','Hotel Mirage',1,80,35,80,'FOUR_STARS',2,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',8,8,1,4,9);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (19,'2022-10-17 00:00:00.000000','2022-10-16 00:00:00.000000','Vincci Capitol',1,130,65,130,'FOUR_STARS',7,'AVION','DOUBLE_ROOM_GARDEN_VIEW','FULL_BOARD',9,9,1,5,10);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (20,'2022-04-25 00:00:00.000000','2022-04-24 00:00:00.000000','H10 Metropolitan',1,150,70,150,'FOUR_STARS',8,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',10,10,1,1,19);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (21,'2022-06-03 00:00:00.000000','2022-06-02 00:00:00.000000','NH Collection',1,135,60,135,'FIVE_STARS',4,'AVION','STANDARD_ROOM','HALF_BOARD',10,10,1,5,20);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (22,'2022-06-04 00:00:00.000000','2022-06-03 00:00:00.000000','Island Escape - SHA Plus',1,250,125,250,'FIVE_STARS',7,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',11,11,2,6,21);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (23,'2022-08-09 00:00:00.000000','2022-08-06 00:00:00.000000','Mai Morn Resort SHA Plus',1,160,90,160,'THREE_STARS',2,'AVION','STANDARD_ROOM','HALF_BOARD',11,11,2,6,22);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (24,'2022-11-04 00:00:00.000000','2022-11-03 00:00:00.000000','Sheraton Grande Sukhumvit',1,225,110,225,'FIVE_STARS',5,'AVION','SUITE','ALL_INCLUSIVE',12,12,2,6,24);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (25,'2022-03-04 00:00:00.000000','2022-03-03 00:00:00.000000','Hotel Monday Premium',1,170,90,170,'FOUR_STARS',8,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',13,13,2,7,25);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (26,'2022-02-24 00:00:00.000000','2022-02-23 00:00:00.000000','Grand Nikko Tokyo Daiba',1,200,105,200,'FIVE_STARS',9,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',13,13,2,7,26);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (27,'2022-04-28 00:00:00.000000','2022-04-27 00:00:00.000000','Karaksa Hotel Grande Shin',1,150,80,150,'FOUR_STARS',3,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',14,14,2,7,27);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (28,'2022-04-25 00:00:00.000000','2022-04-24 00:00:00.000000','Osaka Excel Hotel',1,180,80,180,'FOUR_STARS',5,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',14,14,2,7,28);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (29,'2022-02-11 00:00:00.000000','2022-02-10 00:00:00.000000','Village Hotel Sentosa',1,250,120,250,'FOUR_STARS',3,'AVION','SUITE','HALF_BOARD',15,15,2,8,29);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (30,'2022-03-04 00:00:00.000000','2022-03-03 00:00:00.000000','Hotel Pan Pacific',1,220,110,220,'FIVE_STARS',2,'AVION','STANDARD_ROOM','HALF_BOARD',15,15,2,8,30);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (31,'2022-05-06 00:00:00.000000','2022-05-05 00:00:00.000000','Baros Maldives',1,210,105,210,'FIVE_STARS',5,'AVION','DOUBLE_ROOM_SEA_VIEW','ALL_INCLUSIVE',16,16,2,9,31);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (32,'2022-03-31 00:00:00.000000','2022-03-30 00:00:00.000000','Jen Maldives Male',1,230,110,230,'FOUR_STARS',4,'AVION','SUITE','ULTRA_ALL_INCLUSIVE',16,16,2,9,32);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (33,'2022-06-03 00:00:00.000000','2022-06-02 00:00:00.000000','Riu Plaza Manhattan',1,170,95,170,'FOUR_STARS',3,'AVION','STANDARD_ROOM','HALF_BOARD',17,17,3,10,33);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (34,'2022-03-03 00:00:00.000000','2022-03-02 00:00:00.000000','InterContinental Barclay',1,110,110,250,'FOUR_STARS',4,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',17,17,3,10,34);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (35,'2022-05-06 00:00:00.000000','2022-05-05 00:00:00.000000','East Miami',1,110,90,180,'FIVE_STARS',3,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',18,18,3,10,35);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (36,'2022-02-09 00:00:00.000000','2022-02-08 00:00:00.000000','Hampton Inn&Suites',1,80,80,210,'FOUR_STARS',2,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',18,18,3,10,36);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (37,'2022-06-04 00:00:00.000000','2022-06-03 00:00:00.000000','The Westin Harbour Castle',1,90,90,180,'FOUR_STARS',4,'AVION','STANDARD_ROOM','HALF_BOARD',19,19,3,11,37);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (38,'2022-09-24 00:00:00.000000','2022-09-23 00:00:00.000000','One King West Hotel and Residence',1,140,140,300,'FOUR_STARS',2,'AVION','STANDARD_ROOM','FULL_BOARD',19,19,3,11,38);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (39,'2022-11-04 00:00:00.000000','2022-11-03 00:00:00.000000','Hilton Garden Inn Montreal',1,110,110,190,'FOUR_STARS',4,'AVION','STANDARD_ROOM','FULL_BOARD',20,20,3,11,39);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (40,'2022-12-06 00:00:00.000000','2022-12-05 00:00:00.000000','Hotel Le Cantlie Suites',1,95,95,195,'FOUR_STARS',2,'AVION','STANDARD_ROOM','HALF_BOARD',20,20,3,11,40);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (41,'2022-09-19 00:00:00.000000','2022-09-18 00:00:00.000000','Riu Palace Costa Mujeres',1,150,150,300,'FIVE_STARS',3,'AVION','DOUBLE_ROOM_SEA_VIEW','ALL_INCLUSIVE',21,21,3,12,41);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (42,'2022-04-27 00:00:00.000000','2022-04-26 00:00:00.000000','Planet Hollywood ',1,160,160,280,'FIVE_STARS',2,'AVION','DOUBLE_ROOM_GARDEN_VIEW','FULL_BOARD',21,21,3,12,42);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (43,'2022-03-03 00:00:00.000000','2022-03-02 00:00:00.000000','Hotel Fontan Reforma',1,130,130,215,'FOUR_STARS',5,'AVION','STANDARD_ROOM','HALF_BOARD',22,22,3,12,43);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (44,'2022-02-26 00:00:00.000000','2022-02-24 00:00:00.000000','Fiesta Americana Reforma',1,140,140,280,'FIVE_STARS',5,'AVION','STANDARD_ROOM','FULL_BOARD',22,22,3,12,44);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (45,'2022-11-17 00:00:00.000000','2022-11-16 00:00:00.000000','Hotel Atlantico Tower',1,110,110,265,'FOUR_STARS',7,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',23,23,4,13,45);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (46,'2022-08-18 00:00:00.000000','2022-08-17 00:00:00.000000','Hotel Americas Granada',1,170,170,310,'FOUR_STARS',6,'AVION','STANDARD_ROOM','FULL_BOARD',23,23,4,13,46);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (47,'2022-07-25 00:00:00.000000','2022-07-24 00:00:00.000000','Mercure Sao Paulo',1,170,170,320,'FOUR_STARS',2,'AVION','STANDARD_ROOM','ALL_INCLUSIVE',24,24,4,13,47);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (48,'2022-06-01 00:00:00.000000','2022-05-31 00:00:00.000000','Hotel Maksoud Plaza',1,160,160,320,'FOUR_STARS',1,'AVION','STANDARD_ROOM','FULL_BOARD',24,24,4,13,48);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (49,'2022-03-11 00:00:00.000000','2022-03-10 00:00:00.000000','Hilton Buenos Aires',1,110,110,360,'FIVE_STARS',3,'AVION','STANDARD_ROOM','FULL_BOARD',25,25,4,14,49);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (50,'2022-04-09 00:00:00.000000','2022-04-08 00:00:00.000000','Claridge Hotel',1,170,170,330,'FIVE_STARS',6,'AVION','STANDARD_ROOM','HALF_BOARD',25,25,4,14,50);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (51,'2022-09-06 00:00:00.000000','2022-09-05 00:00:00.000000','Hotel Elegance',1,150,150,330,'FOUR_STARS',2,'AVION','DOUBLE_ROOM_SEA_VIEW','ALL_INCLUSIVE',26,26,4,13,51);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (52,'2022-05-12 00:00:00.000000','2022-05-11 00:00:00.000000','Hotel New Ostende',1,100,100,190,'THREE_STARS',3,'AVION','DOUBLE_ROOM_GARDEN_VIEW','ALL_INCLUSIVE',26,26,4,13,52);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (53,'2022-02-19 00:00:00.000000','2022-02-18 00:00:00.000000','Hotel Brasilia',1,95,95,185,'THREE_STARS',1,'INDIVIDUAL','DOUBLE_ROOM_GARDEN_VIEW','ALL_INCLUSIVE',27,27,4,15,53);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (54,'2022-03-01 00:00:00.000000','2022-02-28 00:00:00.000000','Fondatorul hotelului',1,200,200,310,'FOUR_STARS',2,'AVION','STANDARD_ROOM','BED_AND_BREAKFAST',27,27,4,15,54);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (55,'2022-02-06 00:00:00.000000','2022-02-05 00:00:00.000000','Hotel Diego de Almagro',1,130,130,310,'FOUR_STARS',5,'AVION','DOUBLE_ROOM_GARDEN_VIEW','FULL_BOARD',28,28,4,15,55);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (56,'2022-02-13 00:00:00.000000','2022-02-12 00:00:00.000000','NH Antofagasta',1,180,180,330,'FOUR_STARS',3,'AVION','SUITE','HALF_BOARD',28,28,4,15,56);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (57,'2022-06-11 00:00:00.000000','2022-06-10 00:00:00.000000','Albatros Citadel Resort',1,95,95,190,'FIVE_STARS',3,'AVION','DOUBLE_ROOM_SEA_VIEW','ALL_INCLUSIVE',29,29,5,16,57);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (58,'2022-09-06 00:00:00.000000','2022-09-05 00:00:00.000000','Bel Air Azur Resort',1,85,85,190,'FOUR_STARS',3,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',29,29,5,16,58);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (59,'2022-07-21 00:00:00.000000','2022-07-20 00:00:00.000000','Royal Albatros Moderna',1,100,100,210,'FIVE_STARS',5,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',30,30,5,16,59);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (60,'2022-10-03 00:00:00.000000','2022-10-02 00:00:00.000000','Steigenberger Alcazar',1,80,80,200,'FIVE_STARS',7,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',30,30,5,16,60);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (61,'2022-11-01 00:00:00.000000','2022-10-31 00:00:00.000000','Iberostar Selection Kuriat',1,105,105,220,'FIVE_STARS',4,'AVION','DOUBLE_ROOM_SEA_VIEW','ALL_INCLUSIVE',31,31,5,17,61);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (62,'2022-09-26 00:00:00.000000','2022-09-25 00:00:00.000000','Regency Hotel & Spa',1,103,103,205,'FIVE_STARS',6,'AVION','DOUBLE_ROOM_GARDEN_VIEW','ULTRA_ALL_INCLUSIVE',31,31,5,17,62);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (63,'2022-08-27 00:00:00.000000','2022-08-26 00:00:00.000000','El Mouradi Hotel',1,100,100,230,'FIVE_STARS',5,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',32,32,5,17,63);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (64,'2022-05-31 00:00:00.000000','2022-05-30 00:00:00.000000','Royal Victoria',1,120,120,300,'FIVE_STARS',3,'AVION','SUITE','ULTRA_ALL_INCLUSIVE',32,32,5,17,64);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (65,'2022-03-26 00:00:00.000000','2022-03-25 00:00:00.000000','Hotel Parade',1,90,90,170,'THREE_STARS',2,'AVION','STANDARD_ROOM','FULL_BOARD',33,33,5,18,65);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (66,'2022-06-13 00:00:00.000000','2022-06-12 00:00:00.000000','Blue Waters Hotel',1,105,105,210,'FOUR_STARS',4,'AVION','STANDARD_ROOM','ALL_INCLUSIVE',33,33,5,18,66);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (67,'2022-04-12 00:00:00.000000','2022-04-11 00:00:00.000000','Bliss Boutique Hotel',1,105,105,230,'FOUR_STARS',4,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',34,34,5,18,67);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (68,'2022-02-26 00:00:00.000000','2022-02-25 00:00:00.000000','Radisson Blu Hotel',1,120,120,245,'FIVE_STARS',2,'AVION','STANDARD_ROOM','ULTRA_ALL_INCLUSIVE',34,34,5,18,68);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (69,'2022-03-01 00:00:00.000000','2022-02-28 00:00:00.000000','Eden Lodges',1,120,120,250,'FIVE_STARS',7,'AVION','STANDARD_ROOM','FULL_BOARD',35,35,5,19,69);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (70,'2022-02-06 00:00:00.000000','2022-02-05 00:00:00.000000','Riad Jemaa El Fna',1,130,130,280,'FOUR_STARS',2,'AVION','STANDARD_ROOM','FULL_BOARD',35,35,5,19,70);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (71,'2022-09-07 00:00:00.000000','2022-09-06 00:00:00.000000','BH Appart Hotel',1,110,110,260,'FOUR_STARS',3,'AVION','DOUBLE_ROOM_SEA_VIEW','FULL_BOARD',36,36,5,19,71);
INSERT INTO tour_offer_admin (`id`,`dateOfReturn`,`departureDate`,`name`,`numberOfDays`,`price`,`priceForAChild`,`priceForAnAdult`,`starRating`,`stock`,`travelOption`,`typeOfRooms`,`typeOfService`,`airport_id`,`city_id`,`continent_id`,`country_id`,`hotel_id`) VALUES (72,'2022-08-03 00:00:00.000000','2022-08-02 00:00:00.000000','Casablanca Le Lido Thalasso',1,130,130,280,'FOUR_STARS',5,'AVION','DOUBLE_ROOM_SEA_VIEW','ULTRA_ALL_INCLUSIVE',36,36,5,19,72);